// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Payment struct {
	ID            string
	UserID        string
	AmountInCents int64
	Description   string
	CreatedAt     time.Time
}

type Refund struct {
	ID          string
	PaymentID   string
	UserID      string
	Description string
	RequestedAt time.Time
	UpdatedAt   time.Time
	Status      int64
}
