openapi: 3.1.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  # description: |-
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: auth
  - name: payments
  - name: refunds
host: api.example.com
basePath: /v1
schemes:
  - http
paths:
  /api/users/login:
    post:
      tags:
        - auth
      summary: Log In.
      description: Logs in a user using username/password credentials
      produces:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: A Token Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        404:
          description: Invalid username/password supplied
  /api/payments:
    get:
      tags:
        - payments
      security:
      - bearerAuth: [] # use the same name as above
      summary: Returns a list of payments.
      # description: 
      produces:
        - application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'
        401:
          description: Unauthorized
  /api/refunds:
    get:
      tags:
        - refunds
      security:
      - bearerAuth: [] # use the same name as above
      summary: Returns a list of refunds.
      # description: 
      produces:
        - application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Refund'
    post:
      tags:
        - refunds
      security:
      - bearerAuth: [] # use the same name as above
      summary: Requests a refund.
      # description: 
      produces:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payment_id:
                  type: string
                description:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  payment_id:
                    type: string
                  user_id:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
        400:
          description: Invalid request
        401:
          description: Unauthorized
        404:
          description: Payment not found
components:
  schemas:
    Payment:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        status:
          type: integer
        status_message:
          type: string
        description:
          type: string
        requested_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Refund:
      type: object
      properties:
        id:
          type: string
        payment_id:
          type: string
        user_id:
          type: string
        timestamp:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
